apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: shuy2xp4e-dotnet-basic
  janus-idp.io/tekton: shuy2xp4e-dotnet-basic
  backstage.io/kubernetes-id: shuy2xp4e-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: shuy2xp4e-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
